# 04 - Exploratory Data Analysis (EDA)

## Import Package

In [1]:
# Import package as pandas does not ship along as native package
# use pip install pandas if not installed yet, or follow setup guide

import pandas as pd

In [2]:
dataframe = pd.read_csv("https://raw.githubusercontent.com/KianYang-Lee/pandas-tutorial/main/datasets/Pokemon.csv")
dataframe.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

## Practice Section

Using the `DataFrame` containing only the First Generation of Pokemon, perform EDA to gather information on the following subjects:
- Details of `DataFrame`
- Index
- List of columns
- Descriptive statistics
- Counts for each category for all the categorical columns
- Correlation matrix 
- Top 5 Pokemon with highest speed

In [3]:
first_gen_pokemon = dataframe[dataframe.Generation == 1]

In [5]:
# - Details of `DataFrame`
first_gen_pokemon.info()
# - Index
first_gen_pokemon.index
# - List of columns
first_gen_pokemon.columns
# - Descriptive statistics
first_gen_pokemon.describe()
# - Counts for each category for all the categorical columns
# Get all 'object' data type columns
categorical_cols = first_gen_pokemon.select_dtypes(include=['object']).columns.to_list()
for col in categorical_cols:
    if first_gen_pokemon[col].value_counts().keys().__len__() < 20:
        print(first_gen_pokemon[col].value_counts())
# - Correlation matrix 
first_gen_pokemon.corr()
# - Top 5 Pokemon with highest speed
first_gen_pokemon.nlargest(5, "Speed")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 166 entries, 0 to 165
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           166 non-null    int64
 1   Name        166 non-null    object
 2   Type 1      166 non-null    object
 3   Type 2      78 non-null     object
 4   Total       166 non-null    int64
 5   HP          166 non-null    int64
 6   Attack      166 non-null    int64
 7   Defense     166 non-null    int64
 8   Sp. Atk     166 non-null    int64
 9   Sp. Def     166 non-null    int64
 10  Speed       166 non-null    int64
 11  Generation  166 non-null    int64
 12  Legendary   166 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 17.0+ KB
Water       31
Normal      24
Fire        14
Bug         14
Poison      14
Grass       13
Psychic     11
Rock        10
Electric     9
Ground       8
Fighting     7
Ghost        4
Dragon       3
Fairy        2
Ice          2
Name: Type 1, dtype: int64
Flying      23
Poison      22
Psychic      7
Ground       6
Water        4
Fairy        3
Ice          3
Grass        2
Fighting     2
Steel        2
Rock         2
Dragon       1
Dark         1
Name: Type 2, dtype: int64

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
109,101,Electrode,Electric,NaN,480,60,50,70,80,80,140,1,False
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True

**Copyright (C) 2021  Lee Kian Yang**

This program is licensed under MIT license.